### ISSUE TITLE
GZip files

### ISSUE THREAD

**Issue by raceloop** [stojanovic/scottyjs#14]
Nice tool! 

Given that S3 does not compress assets served from the bucket it would be very handy to have a switch to pre compress uploaded assets to S3.

**Comment by simalexan** [comment]
good idea! want to try to submit a PR?

**Comment by MaxGraey** [comment]
What about brotli?

**Comment by stojanovic** [comment]
No need for an external dependency, Node has zlib that can do gzip: https://nodejs.org/api/zlib.html

**Comment by amirilovic** [comment]
@stojanovic Is this really needed since [CF already does compression](https://github.com/stojanovic/scottyjs/blob/cb404f0d58af9eb9c5d581218f3ca99862a8a75e/lib/set-cdn.js#L33)? 

From the docs: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

**Comment by stojanovic** [comment]
@amirilovic you are right, thanks!

<img width="532" alt="screen shot 2017-08-31 at 2 10 35 am" src="https://user-images.githubusercontent.com/613478/29900360-adeb0940-8df1-11e7-9415-1cc67535bb46.png">

**Comment by raceloop** [comment]
Hi, sorry to chime in so late.

Yes, Cloud front already does this. I was trying to avoid cloudfront but it turns out that this is not as straight forward as I first thought. S3 tries to automatically tries detect the content type and for uploaded files so for zip files this is set to octet regardless of the underlying file. Thus, each file needs to be uploaded individually whilst setting the content type.

In the end, I agree that it's not worth it when cloudfront does it for you. 

Cheers

JT

**Comment by stojanovic** [comment]
Each file is uploaded separately anyway, but Scotty assumes CDN url will be used for production, so I agree with @amirilovic that gzip is not really necessary.

Not sure if anyone wants to deploy final website without CDN, I guess the only reason would be cutting cost? But for S3 only deployment `aws s3 sync` command can be used, so it probably doesn't make sense to add gzip feature to Scotty, because it will not make any difference.
