### ISSUE TITLE
Configure credentials via command line. Proposal

### ISSUE THREAD

**Issue by MaxGraey** [stojanovic/scottyjs#9]
Example:

```
scotty --spa --source ./build --access-key-id AKIAIOSFODNN7EXAMPLE --secret-access-key wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```

or
```
scotty --spa --source ./build --config ./scotty-config.json
```

**scotty-config.json:**
```json
{
     "region": "<region>",
     "access-key-id": "<key>",
     "secret-access-key": "<key>"
}
```

And use ```AWS.config.loadFromPath``` or ```new AWS.Config(options)``` according to define credential style

**Comment by stojanovic** [comment]
That's planned for the next major version. We will not provide flags, but we are planning to do prompt if profile doesn't exist and to save credentials in the default AWS location. But we'll see if we can do that.

Other thing that will be provided is `--profile` flag, for now you need to set the profile with env variable, ie. `AWS_PROFILE=scotty-profile scotty --spa`.

**Comment by MaxGraey** [comment]
It will be great. I prefer use local config without aws cli.

**Comment by stojanovic** [comment]
It can be useful for CI or something like that. Maybe `--config` makes sense.
Thanks for proposing it.

**Comment by ckaatz-here** [comment]
I like the --config flag as it could contains also more props like domain, permissions etc...

**Comment by stojanovic** [comment]
Well, idea for scotty v2 is a bit different:

1. When you run `scotty` it will take you through the few questions, ie. credentials, region, website or spa, etc. And it will create `scotty.json` file in your project
2. When you run `scotty` again, it will simply use config from that file and update the project.

So domain and other similar things will be handled on local file level, other config is mostly for AWS credentials. But we still need to see if that is useful at this point, because you can set credentials with env variables.

**Comment by stojanovic** [comment]
This issue will be addressed in v2, hopefully soon.
I am closing it now.

**Comment by MaxGraey** [comment]
ок
